<a href="https://colab.research.google.com/github/maryamalka85/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# create random tensor
X = torch.rand(size=(7,7))
X,X.shape

(tensor([[0.3142, 0.4865, 0.7705, 0.3263, 0.7264, 0.6868, 0.0522],
         [0.5438, 0.9234, 0.6737, 0.3396, 0.4684, 0.9051, 0.9022],
         [0.5038, 0.2225, 0.9657, 0.4975, 0.0989, 0.6913, 0.5937],
         [0.7634, 0.8749, 0.1176, 0.0565, 0.5362, 0.1045, 0.6571],
         [0.2290, 0.1231, 0.1060, 0.2285, 0.8602, 0.9666, 0.6981],
         [0.5703, 0.9126, 0.0165, 0.9157, 0.9846, 0.1595, 0.7734],
         [0.0339, 0.1776, 0.6518, 0.5989, 0.2043, 0.2849, 0.2325]]),
 torch.Size([7, 7]))

In [ ]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Perform matrix multiplication
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.4617],
         [1.7799],
         [1.3014],
         [0.9893],
         [1.7503],
         [1.7336],
         [0.8774]]),
 torch.Size([7, 1]))

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [ ]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617), tensor(0.3647))

In [ ]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
