## Arewa DataScience Academy
### Deep Learning Cohort 1.0
### Name : mohammed nasiru
### Email : katada3020@gmail.com

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

### Additional Exercise

In [2]:
#imports
import torch

1 Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

In [3]:
#2. Create a random tensor with shape (7, 7)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.2786, 0.6433, 0.9123, 0.4081, 0.0929, 0.5872, 0.5338],
        [0.5620, 0.3224, 0.7754, 0.4435, 0.6841, 0.5883, 0.1725],
        [0.5943, 0.1253, 0.6376, 0.8613, 0.3860, 0.9380, 0.1353],
        [0.7254, 0.4970, 0.3879, 0.9906, 0.1109, 0.0274, 0.8096],
        [0.4879, 0.9880, 0.8715, 0.6121, 0.2404, 0.3733, 0.8164],
        [0.3921, 0.8757, 0.3678, 0.7095, 0.7479, 0.2668, 0.0350],
        [0.4320, 0.0892, 0.9823, 0.6301, 0.6586, 0.4471, 0.0691]])

In [4]:
#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
random_tensorB = torch.rand(1,7)
new_tensor = torch.matmul(random_tensor,random_tensorB.T)
new_tensor

tensor([[1.3707],
        [1.2681],
        [1.4721],
        [0.8596],
        [1.4368],
        [1.0763],
        [1.2253]])

In [8]:
#4. Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
random_tensorA = torch.rand(7,7)
random_tensorB = torch.rand(1,7)
new_tensor = torch.matmul(random_tensorA,random_tensorB.T)
new_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [6]:
cuda_is_available = torch.cuda.is_available
if cuda_is_available:
  cuda_version = torch.version.cuda
  print(f'cuda is available {cuda_is_available}')

cuda is available <function is_available at 0x7aa3349b8c10>


In [7]:
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
random_tensorA = torch.rand(7,7)

In [8]:

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(1234)
else:
    print("GPU not available, setting only CPU seed.")

torch.manual_seed(1234)

GPU not available, setting only CPU seed.
