<a href="https://colab.research.google.com/github/katada3020/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/exercise_submissions/week_1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype

(tensor([[0.8861, 0.4586, 0.8887, 0.5278],
         [0.9070, 0.9829, 0.8053, 0.8296],
         [0.3199, 0.0335, 0.7847, 0.2212]]),
 torch.float32)

In [ ]:
!git clone https://github.com/katada3020/ArewaDS-Deep-Learning

fatal: destination path 'ArewaDS-Deep-Learning' already exists and is not an empty directory.


In [ ]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [ ]:
!!git clone https://github.com/katada3020/ArewaDS-Deep-Learning

["Cloning into 'ArewaDS-Deep-Learning'...",
 'remote: Enumerating objects: 85, done.\x1b[K',
 'remote: Counting objects:   1% (1/85)\x1b[K',
 'remote: Counting objects:   2% (2/85)\x1b[K',
 'remote: Counting objects:   3% (3/85)\x1b[K',
 'remote: Counting objects:   4% (4/85)\x1b[K',
 'remote: Counting objects:   5% (5/85)\x1b[K',
 'remote: Counting objects:   7% (6/85)\x1b[K',
 'remote: Counting objects:   8% (7/85)\x1b[K',
 'remote: Counting objects:   9% (8/85)\x1b[K',
 'remote: Counting objects:  10% (9/85)\x1b[K',
 'remote: Counting objects:  11% (10/85)\x1b[K',
 'remote: Counting objects:  12% (11/85)\x1b[K',
 'remote: Counting objects:  14% (12/85)\x1b[K',
 'remote: Counting objects:  15% (13/85)\x1b[K',
 'remote: Counting objects:  16% (14/85)\x1b[K',
 'remote: Counting objects:  17% (15/85)\x1b[K',
 'remote: Counting objects:  18% (16/85)\x1b[K',
 'remote: Counting objects:  20% (17/85)\x1b[K',
 'remote: Counting objects:  21% (18/85)\x1b[K',
 'remote: Counting objects:  22% (

In [ ]:
!cd ArewaDS-Deep-Learning
!ls

ArewaDS-Deep-Learning  drive  sample_data


In [ ]:
#create a tensor of all zeroes
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1 )
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeroes = torch.zeros_like(input=zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
float_32_tensors = torch.tensor([3.0,6.0,9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)


In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensors = torch.tensor([3.0,6.0,9.0],
                                dtype = torch.float16)
float_16_tensors.dtype

torch.float16

In [ ]:
some_tensors = torch.rand(3,4)
print(some_tensors)
print(f'shape of tensor : {some_tensors.shape}')
print(f'the type of tensor : {some_tensors.dtype}')

tensor([[0.4492, 0.4965, 0.7988, 0.7164],
        [0.5437, 0.7488, 0.8945, 0.2881],
        [0.9690, 0.3462, 0.1839, 0.5875]])
shape of tensor : torch.Size([3, 4])
the type of tensor : torch.float32


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 11

tensor([11, 22, 33])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
torch.add(tensor,20)

tensor([21, 22, 23])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]], dtype = torch.float32)
tensorB = torch.tensor([[7,8],
                        [9,10],
                        [11,12]], dtype = torch.float32)
torch.matmul(tensorA,tensorB)


RuntimeError: ignored

In [ ]:
x = torch.arange(0,100,10)
print(f'mininim : {x.min()}')
print(f'maximum : {x.max()}')
print(f'mean : {x.type(torch.float32).mean()}')

mininim : 0
maximum : 90
mean : 45.0


In [ ]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
import torch
import random


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(seed= RANDOM_SEED)
random_tensor_c = torch.rand(3,4)



In [ ]:
!git init
!git clone https://github.com/katada3020/ArewaDS-Deep-Learning

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
Cloning into 'ArewaDS-Deep-Learning'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 85 (delta 20), reused 49 (delta 5), pack-reused 0
Receiving objects: 100% (85/85), 10.80 MiB | 7.46 MiB/s, done.
Resolving deltas: 100% (20/20), done.


In [ ]:
!cd /content/ArewaDS-Deep-Learning/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb

/bin/bash: line 1: cd: /content/ArewaDS-Deep-Learning/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb: No such file or directory


In [ ]:
j